#!/bin/bash
# Usage: run_sim_gps <proc> <particle>
set -o errexit

# Input simulation parameters
particle="$2"
energies=(1 2 5 10 20 30 40 50 60 70 80 90 100)
j=$(( $1 % 10 ))
k=$(( $1 / 10 ))
beam_energy=${energies[$k]}
min_e=$(echo "$beam_energy * 0.1" | bc)
num_events=1000
theta_low=177.17
theta_high=177.17
phi_low=0
phi_high=360

gps_file="gps.mac"
OUTDIR=$SPIN/data/eic/insert
mkdir -p ${OUTDIR}
mkdir -p proc$1
cd proc$1

# Output file names
compact_file=../endcapP_insert.xml
info_string="${particle}_${beam_energy}GeV_theta_${theta_low}deg_${theta_high}deg"
sim_file="${OUTDIR}/sim_${info_string}.root"
reco_file="${OUTDIR}/reco_${info_string}.edm4hep.root"

# Putting parameters into gps file
cp ../$gps_file .
sed -i "s/\/gps\/particle .*/\/gps\/particle ${particle}/" $gps_file
sed -i "s/\/gps\/ene\/mono .*/\/gps\/ene\/mono ${beam_energy} GeV/" $gps_file
sed -i "s/\/gps\/ang\/mintheta .*/\/gps\/ang\/mintheta ${theta_low} degree/" $gps_file
sed -i "s/\/gps\/ang\/maxtheta .*/\/gps\/ang\/maxtheta ${theta_high} degree/" $gps_file
sed -i "s/\/gps\/ang\/minphi .*/\/gps\/ang\/minphi ${phi_low} degree/" $gps_file
sed -i "s/\/gps\/ang\/maxphi .*/\/gps\/ang\/maxphi ${phi_high} degree/" $gps_file
sed -i "s/\/run\/beamOn .*/\/run\/beamOn $num_events/" $gps_file

# Running simulation
npsim --runType run \
      -v WARNING \
      --part.minimalKineticEnergy "${min_e}*GeV" \
      --physics.list "FTFP_BERT_HP" \
      --physics.rangecut "None" \
      --compactFile ${compact_file} \
      --enableG4GPS \
      --macroFile ${gps_file} \
      --outputFile ${sim_file}

cd ..
rm -rf proc$1
