#!/bin/bash
# Usage: run_sim_hepmc <proc> <particle>
set -o errexit

# Input simulation parameters
particle="$2"
energies=(80) #(1 2 5 10 20 30 40 50 60 70 80 90 100)
j=$(( $1 % 100 ))
k=$(( $1 / 100 ))
beam_energy=${energies[$k]}
min_e=$(echo "$beam_energy * 0.1" | bc)
num_events=1000
theta_min=15 #2.83 # in degrees
theta_max=20 #2.83 # in degrees
phi_min=0 # in degrees
phi_max=360 # in degrees 
physics_list="FTFP_BERT_HP"

OUTDIR=$SPIN/data/eic/endcap
mkdir -p ${OUTDIR}

# Output file names
compact_file=./endcapP_insert.xml
info_string="${particle}_${beam_energy}GeV_theta_${theta_min}_${theta_max}deg-$j"
hepmc_file="${OUTDIR}/gen_${info_string}.hepmc"
sim_file="${OUTDIR}/sim_${info_string}.root"
reco_file="${OUTDIR}/reco_${info_string}.edm4hep.root"

# Generating hepmc file
root -l -b -q "./hepmc_generation/gen_particles.cxx+(\
${num_events},\
\"${hepmc_file}\",\
\"${particle}\",\
${theta_min},\
${theta_max},\
${phi_min},\
${phi_max},\
${beam_energy})"

# Running simulation
npsim --runType batch \
      -v WARNING \
      --part.minimalKineticEnergy "${min_e}*GeV" \
      --physics.list "FTFP_BERT_HP" \
      --physics.rangecut "None" \
      --numberOfEvents ${num_events} \
      --compactFile ${compact_file} \
      --inputFiles ${hepmc_file} \
      --outputFile ${sim_file}

# Deleting hepmc_file
rm ${hepmc_file}
