#!/bin/bash

# Input simulation parameters
particle="pi-"
beam_energy=40
num_events=1000
theta=2.83 # theta in degrees

# Output file names
info_string="${particle}_${beam_energy}GeV_theta_${theta}deg"
hepmcfile="gen_${info_string}.hepmc"
simfile="insert_sim_${info_string}.root"
recofile="insert_reco_${info_string}.edm4hep.root"

# Generating hepmc file
root -l -b -q "./hepmc_generation/gen_particles.cxx+(\
${num_events},\
\"${hepmcfile}\",\
\"${particle}\",\
${theta},\
${beam_energy})"

# Running simulation
npsim \
   --compactFile endcapP_insert.xml \
   --numberOfEvents ${num_events} \
   --inputFiles ${hepmcfile} \
   --outputFile ${simfile}  || exit
   
# Deleting hepmcfile  
rm ${hepmcfile}

# Running reconstruction
export JUGGLER_SIM_FILE=${simfile} JUGGLER_REC_FILE=${recofile} JUGGLER_N_EVENTS=${num_events}
gaudirun.py endcapP_insert_reco.py