/control/verbose 2
/run/initialize

/gps/verbose 2
/gps/particle pi-
/gps/number 1

/gps/ene/type Gauss
/gps/ene/mono 50 GeV

/gps/pos/type Volume
/gps/pos/shape Cylinder
/gps/pos/centre -10. 0.0 0.0 cm
/gps/pos/radius 0.01 cm
/gps/pos/halfz  10 cm
 
/gps/ang/type iso
/gps/ang/mintheta 177.17 degree
/gps/ang/maxtheta 177.17 degree
/gps/ang/minphi 0 degree
/gps/ang/maxphi 360 degree

/run/beamOn 1000
